### ISSUE TITLE
Can anyone help me understand how to use the generate feature?

### ISSUE THREAD

**Issue by theloneamigo** [Aidymouse/Hexfriend#19]
Great hexmapping tool! I'm really enjoying it - however...

...as far as I can tell, the generate feature does nothing. I don't understand how it's meant to function, and when I press the Generate button, no matter how much I muck around with the Generate recipe (I'm assuming it does something like converts Grass squares to X (weight % chance) or Y (weight % chance) but I can't tell) - it does absolutely nothing.

Might be undocumented, might be a bug. Can anyone help me understand?

**Comment by Aidymouse** [comment]
This was broken until version 1.7. It works now, but I'm not sure it's very intuitive.

Basically, the generator will randomly walk around the map. The tile generated depends on the tile the generator is coming from. Each row in the generator is essentially the pool of hexes that can be generated if the generator is generating a new hex from that tile. Imagine it like a bag of tiles. When the generator walks from, say, a grass tile into a blank tile, it looks up the row for grass tile, picks a random tile from the bag, and places it on the ground. It then does this for the next tile.

Thanks for flagging this issue! It was on my to do list for a long time.
