### ISSUE TITLE
Tiles only being place in pairs

### ISSUE THREAD

**Issue by GeorgeZack** [Aidymouse/Hexfriend#24]
When I create a new hexmap and place a tile it does not show until I place another. Seems to only be in pairs that tiles will update.

**Comment by GeorgeZack** [comment]
Hmm, I can no longer replicate. I wonder if my Chromium instance was runng out of memory. Never mind!

**Comment by GeorgeZack** [comment]
I closed this because it was working for me. But further testing resulted in errors. I'm on Brave/Chromium, but it seems that FireFox works.

**Comment by Aidymouse** [comment]
Could you share some details about how the error occurs? It's working on Chrome and Brave for me. I do get a similar bug when using the website with a touch screen, and pointer events were recently changed to Mouse events. Could have something to do with that?

**Comment by GeorgeZack** [comment]
Unable to replicate again. I'm not sure why this happened. Mouse events seem to be fine for me. I started whipping up a large map and changing the size of the map in the middle of making it, but it was working fine.
