### ISSUE TITLE
I want do add localization to Brazilian Portuguese

### ISSUE THREAD

**Issue by igorteuri** [Aidymouse/Hexfriend#34]
Hello there!

Amazing work. Is there any way for me to contribute voluntarily by adding a Brazllian Portuguese localization?

**Comment by Aidymouse** [comment]
You are legendary. I will look into how localization works (I haven't done it before) and how you can contribute.

**Comment by Aidymouse** [comment]
Alright, I've done some work on this. The translation branch now loads a bunch of terms from a seperate file which you should be able to use to translate most of the buttons and labels. The words currently aren't used everywhere, I'll go and patch those through over time (it's quite tedious and I'm low on time) but the file that the translations will draw from is complete, which means you can be translating while I work on the boring bits.

[This file](https://github.com/Aidymouse/Hexfriend/blob/translation/src/lib/translations/pt_br.ts) will be used to translate. Feel free to pull, edit and submit a pull request.

I know translation isn't the only part of localization, so let me know if there is anything else you think should be changed to better support Brazilian Portuguese. That said, Hexfriend is fairly simple, so hopefully translation should be a good bit of the way there. ✌️

**Comment by igorteuri** [comment]
I've trasnlated it and opened a pull request.

**Comment by igorteuri** [comment]
I've translated it and opened a pull request.
