### ISSUE TITLE
Contribution and Community

### ISSUE THREAD

**Issue by BigJk** [Aidymouse/Hexfriend#5]
Hello Aidymouse,

I really like the Project and would be interested in contributing. Do you thought about creating a dedicated Discord Server to make organisation around the project a bit easier?

**Comment by Aidymouse** [comment]
Hi there!

Sorry I took so long, University started again and I got busy.
However, I have set up a preliminary discord, you can join here: [https://discord.gg/Jvws27VmWR](https://discord.gg/Jvws27VmWR)

Looking forward to working with you!
